project:
  type: book
  post-render: _render_presentation.R

book:
  title: "Agentic Code Review and Validation"
  subtitle: "An Introduction to Agentic Coding Assistants"
  date: "August 30, 2026"
  date-format: long 
  author:
    - name: Janick Weberpals, RPh, PhD
      corresponding: true
      orcid: 0000-0003-0404-7394
      email: 
      url: janickweberpals.github.io
      affiliations:
        - name: 
          address: 
          city: 
  chapters:
    - index.qmd # landing page
    - part: "Mock study"
      chapters:
        - mock-study/01_csp.qmd
        - mock-study/03_primary_endpoint_analysis.qmd
        - mock-study/04_validation.qmd
  reader-mode: true
  repo-url: https://github.com/janickweberpals/agentic-code-review-ispe-2026
  repo-actions: [issue]

format:
  html:
    embed-resources: true
    code-fold: true
    code-summary: "Show the code"
    theme: cosmo
    engine: knitr
    page-layout: full
    link-external-icon: true
    link-external-newwindow: true
    # comments:
    #   hypothesis: true

bibliography: references.bib
csl: pharmacoepidemiology-and-drug-safety.csl

